# Manager
[manager]
cwd = { fg = "#cccccc" }

hovered         = { fg = "#000000", bg = "#ffffff" }
preview_hovered = { fg = "#000000", bg = "#ffffff", underline = true }

find_keyword  = { fg = "#ffffff", bold = true, underline = true }
find_position = { fg = "#ffffff", bg = "#000000", bold = true }

marker_copied   = { fg = "#000000", bg = "#ffffff" }
marker_cut      = { fg = "#000000", bg = "#ffffff" }
marker_marked   = { fg = "#000000", bg = "#ffffff" }
marker_selected = { fg = "#000000", bg = "#ffffff" }

tab_active   = { fg = "#000000", bg = "#ffffff" }
tab_inactive = { fg = "#777777", bg = "#000000" }
tab_width    = 1

count_copied   = { fg = "#000000", bg = "#ffffff" }
count_cut      = { fg = "#000000", bg = "#ffffff" }
count_selected = { fg = "#000000", bg = "#ffffff" }

border_symbol = "â”‚"
border_style  = { fg = "#4a4a4a" }

# Mode
[mode]

normal_main = { fg = "#000000", bg = "#e0e0e0", bold = true }
normal_alt  = { fg = "#e0e0e0", bg = "#202020" }

select_main = { fg = "#000000", bg = "#ffffff", bold = true }
select_alt  = { fg = "#ffffff", bg = "#202020" }

unset_main  = { fg = "#000000", bg = "#d0d0d0", bold = true }
unset_alt   = { fg = "#d0d0d0", bg = "#202020" }

# Status bar
[status]
perm_sep   = { fg = "#7f7f7f" }
perm_type  = { fg = "#bbbbbb" }
perm_read  = { fg = "#dddddd" }
perm_write = { fg = "#cccccc" }
perm_exec  = { fg = "#ffffff" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#ffffff", bg = "#4a4a4a" }
progress_error  = { fg = "#ffffff", bg = "#4a4a4a" }

# Pick
[pick]
border   = { fg = "#4a4a4a" }
active   = { fg = "#ffffff", bold = true }
inactive = {}

# Input
[input]
border   = { fg = "#4a4a4a" }
selected = { fg = "#000000", bg = "#ffffff" }

# Completion
[cmp]
border = { fg = "#4a4a4a" }

# Tasks
[tasks]
border  = { fg = "#4a4a4a" }
hovered = { fg = "#ffffff", underline = true }

# Which
[which]
mask            = { bg = "#202020" }
cand            = { fg = "#ffffff" }
rest            = { fg = "#cccccc" }
desc            = { fg = "#ffffff" }
separator       = ">"
separator_style = { fg = "#4a4a4a" }

# Help
[help]
on      = { fg = "#ffffff" }
run     = { fg = "#ffffff" }
hovered = { fg = "#000000", bg = "#ffffff", bold = true }
footer  = { fg = "#000000", bg = "#e0e0e0" }

# Notify
[notify]
title_info  = { fg = "#ffffff" }
title_warn  = { fg = "#ffffff" }
title_error = { fg = "#ffffff" }

# Filetypes
[filetype]
rules = [
	{ mime = "image/*", fg = "#cccccc" },
	{ mime = "{audio,video}/*", fg = "#cccccc" },
	{ mime = "application/*", fg = "#cccccc" },
	{ name = "*", fg = "#ffffff" },
	{ name = "*/", fg = "#ffffff" },
]
